[FIREBASE_CREDENTIALS]
type = 'service_account'
project_id = 'streamlit-b5213'
private_key_id = '73e0ed38885423aab4caa19da2aac9332b351a66'
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCac9QzFSoGuBk+\nNavNnk7R9tDp8enhKtiW00HuqT+CkQE3qjldVb0GwO0oIV32hmYCg7HIQ27w6npd\nWMBthe+aE/6DQVThKw/9HvxraXjH6tuBwyOgqy0/xGcPS2TvJsK6nZACfQPOBynN\n0m7fFUeJdG6ZoEBrimKO40nqTwGNDPP7EXJOGJPTl1+HOSIrrtmUFtke/6wHeX1a\nt+S3sa6hZoiQ0tAfSBL0q9GNmnzw2mRuayi8bimFtYr9wE3gFdY1ppreYlX8sldF\n269EC83FgieyPunDqS5SmueGHBHpqn4KsTfOXWunkZ82m1MiBt2EPKo8ffNtLuHK\nUw9Olh37AgMBAAECggEAEmxCLEJYLCCrI3r7vlUlj1uH3tJ+tF92d0MaqFuNb5xZ\nOf5hb6B0TB5uC1feNojLGSiukjXM7Aqj7tzREx9N4vct6BJpC/Slfb/uRDz6mFS2\nEHEqH5YwxFw/yMNpoNxi5NHk0A8rtC2xjv3h61UanoAsrcFqKF8DfjSz59wQUiEW\nc1AlmXjyQsQjiLglzW0HpGj6I1luAiqN3JCf/vqYU+wTCyNiVioGtNPBYLadfthU\nDV2eywksoAt6/J0MvdQIJYgNztsETmIK6C+B/xLxjhcT4SdWfXC2GT1rh2Jkd8Mq\nvX90HNsLj+mzogy8FjeIQe03xNYL61ENEoii+pXe6QKBgQDL8PJvxHmvIvgfUQx+\nMUplauA9Saxx4w5p/F9X9XxQwyGD3wKduFgKqmeX9zm8GFo81NgPzPvtpC+AjlQ6\nRyRyKeKL+w4tfLcg3RIfmaChQFWRhRmI0g8HNYTfPnk5MqqA4UXRD6M0DsdJ/Xsz\n6qcWDW4H5you0k2Yy+apyI5IYwKBgQDB4Oo6TeQ4NpwyBRKz+/V6XQMRCkm8FyMA\nOofMYqw+j2dVmRzGQ+KJ71/dBmTqm1JFo+atWJ0KsOp+3SDUsneDSpZQWBwlymE5\nsAdmkbZAPTdOqZ2e7AdAwHTc7slm2VJE7337gtSvodTKAFVGDVUIdc2+VkAOVOiT\nRoMj1BBriQKBgGhsnmZ2TuxLVosKgAAZkwNs/xbCo4bJATdpnxQ1wYrE72NLjFZf\n7sy/Rj38u9ZBDet5/IvSpOigmiYUOrKAfPvr0HFmgnLuGgK8z6vYiPQoMehKI7H4\nBPPnBnsczQtpkv5c2tfaTvG343lSToRd0WIsTDvFtMa2rj7foOMsqxYLAoGAMTqs\nHwviNEfhl23kVuFWbrCpc606FdGGKKu0CbjQZb5CDeEoBkv8fOvUWqoh+9ReqqI4\nk7GZhrpvgLEjgf6jDCpnSpVk6E+gKmbBKlE7hspEfevhwxXJra5wvhy/9SafljN9\nuNx6pvIftv8op/YArnpDON5ru3fh6muQJwvU84kCgYEAwlyCTSSW5CMtb36S6235\nAeJriPb4jg+89woW7R8grEg1oSz8OkFZSZWqzKASDU9aZSPrleP7OUVv+mmi0Evg\nEHT6inPPhDRvECgdkzYwgh4T0j9o+P7wT/D85NoQdDZWgFVC5/ERdYS+KoUYZ4g2\nRqwUHPSz7TB2kwXAegF/jcw=\n-----END PRIVATE KEY-----\n"
client_email = 'firebase-adminsdk-o92xi@streamlit-b5213.iam.gserviceaccount.com'
client_id = '111203315060042107660'
auth_uri = 'https://accounts.google.com/o/oauth2/auth'
token_uri = 'https://oauth2.googleapis.com/token'
auth_provider_x509_cert_url = 'https://www.googleapis.com/oauth2/v1/certs'
client_x509_cert_url = 'https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-o92xi%40streamlit-b5213.iam.gserviceaccount.com'
universe_domain = 'googleapis.com'

[GOOGLE_SHEET_CREDENTIALS]
type = ''
project_id = ''
private_key_id = ''
private_key = ""
client_email = ''
client_id = ''
auth_uri = ''
token_uri = ''
auth_provider_x509_cert_url = ''
client_x509_cert_url = ''
universe_domain = ''